language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - ruby-head
script: "bundle exec rspec spec"
before_script:
  - "mysql -e 'create database spud_banners_test;'"
  - "bundle exec rake db:schema:load"
  - "bundle exec rake app:db:test:prepare"
